### ISSUE TITLE
kafka cluster info not show 

### ISSUE THREAD

**Issue by zfq314** [smartloli/EFAK#453]
![image](https://user-images.githubusercontent.com/33599707/102716960-268e4200-431a-11eb-8ecf-cd53ebce9ab3.png)
kafka的信息无法获取，请问怎么回事，kafka可以生产和消费消息

**Comment by smartloli** [comment]
Please enable kafka `JMX_PORT `

and watch `$KE_HOME/logs/ke_console.out`

**Comment by zfq314** [comment]
I set JMX_PORT=9999
But i didn't see it
