### ISSUE TITLE
centos 运行出错 ke.sh: line 128: /root/kafka-eagle-bin-2.0.8/efak-web-2.0.8/bin/ke.pid: No such file or directory

### ISSUE THREAD

**Issue by yuanxingkang** [smartloli/EFAK#565]
inflated: media/css/bscreen/font/DS-DIGIT.TTF
 inflated: media/css/bscreen/css/bscreen.css
  created: META-INF/maven/
  created: META-INF/maven/org.smartloli.kafka.eagle/
  created: META-INF/maven/org.smartloli.kafka.eagle/efak-web/
 inflated: META-INF/maven/org.smartloli.kafka.eagle/efak-web/pom.xml
 inflated: META-INF/maven/org.smartloli.kafka.eagle/efak-web/pom.properties
[2021-11-05 10:32:02] INFO: Port Progress: [##################################################] | 100%
[2021-11-05 10:32:05] INFO: Config Progress: [##################################################] | 100%
[2021-11-05 10:32:08] INFO: Startup Progress: [##################################################] | 100%
[2021-11-05 10:31:57] INFO: Status Code[0]
[2021-11-05 10:31:57] INFO: [Job done!]
Welcome to
    ______    ______    ___     __ __
   / ____/   / ____/   /   |   / //_/
  / __/     / /_      / /| |  / ,<   
 / /___    / __/     / ___ | / /| |  
/_____/   /_/       /_/  |_|/_/ |_|  
( Eagle For Apache Kafka® )

Version 2.0.8 -- Copyright 2016-2021
*******************************************************************
* EFAK Service has started success.
* Welcome, Now you can visit 'http://172.29.68.202:8048'
* Account:admin ,Password:123456
*******************************************************************
* <Usage> ke.sh [start|status|stop|restart|stats] </Usage>
* <Usage> https://www.kafka-eagle.org/ </Usage>
*******************************************************************
ke.sh: line 128: /root/kafka-eagle-bin-2.0.8/efak-web-2.0.8/bin/ke.pid: No such file or directory
![image](https://user-images.githubusercontent.com/93037616/140448587-b08bcf62-37b5-45f0-9aec-c8bbbe218c71.png)

**Comment by wildChicken96** [comment]
怎么解决的呢？
