### ISSUE TITLE
2.0.8版本监控时间排序错乱

### ISSUE THREAD

**Issue by che302956637** [smartloli/EFAK#566]
![eagle](https://user-images.githubusercontent.com/8772901/140741016-50294c88-6da8-46d4-a546-b9995ddd68e9.png)
EFAK 2.0.8版本，在Consumer菜单中查看topic消费监控情况，出现时间轴未排序的情况（已确认系统时间正常）

**Comment by linux-ops** [comment]
默认按照数据量大小排序，非时间排序，如果希望按照排序的话，修改源码里面的SQL语句.

https://github.com/smartloli/EFAK/pull/518/commits/6ac5a646006e274fe96c8f140de696c29996c992

**Comment by linux-ops** [comment]
[https://github.com/smartloli/EFAK/pull/518/commits/6ac5a646006e274fe96c8f140de696c29996c992](url)

**Comment by che302956637** [comment]
多谢！已修改ke.war中这两个xml文件并重启，问题得到解决
这并非一个bug，但从使用角度上看，还是希望能优化这一点，或增加用户自己选择排序的方式

**Comment by linux-ops** [comment]
还是有一些东西需要优化的，目前发现的问题已Fix掉.

1、修复平台前端消息写入、消费、延迟时间轴乱序问题
2、修复非活跃成员的 Consumer Group 产生的Lag报警
3、修复Kafka Service DELETE Consumer Group Id 遗留到报警策略问题
4、修正Consumer Group 自动添加监控策略，排除掉非活跃成员Group.
5、修正Consumer Group ID  非固定场景，产生的Lag误报问题。

**Comment by che302956637** [comment]
非常感谢，也正在向身边的同事推广EFAK工具~

**Comment by zzf1208** [comment]
> [https://github.com/smartloli/EFAK/pull/518/commits/6ac5a646006e274fe96c8f140de696c29996c992](url)

您好 想知道要修改这个监控时间排序错乱，需要修改那个文件更改默认排序
