### ISSUE TITLE
监控kafka producer 是否正常

### ISSUE THREAD

**Issue by lordk911** [smartloli/EFAK#640]
想要监控kafka producer，如果1分钟内发送的消息是0，则报警：
样例的配置：{"topic":"ke_alarm_topic","speed":"10000,20000"}.  没看明白是什么意思，是指每分钟1万或2万都报警吗？
我设置了监控条件：
{"topic":"aplog_beijing","speed":"0"}.
收到的告警信息为：

```
EFAK - Alert Cluster Error 
AlarmID : [ 1 ]
AlarmCluster : [ hdp20 ]
AlarmStatus : [ PROBLEM ]
AlarmLevel : [ P3 ]
AlarmProject : [ Producer ]
AlarmTimes : [ current(1), max(1) ]
AlarmDate : [ 2022-08-30 12:40:00 ]
AlarmContent : [ producer.speed.overflow [topic(aplog_beijing), real.speeds(680), alarm.speeds.range(0,0)] ]
```

real.speeds(680) 说明有数据，为什么还告警？

**Comment by zhugezifang** [comment]
"speed":"10000,20000"  代表数据产出速度在这个范围内不报警，其他的都会报警
